schedule: '"*/30 * * * *"'
restartPolicy: OnFailure
successfulJobsHistoryLimit: 3

nameOverride: ""
fullnameOverride: ""

image:
  name: ghcr.io/omegion/vault-unseal
  tag: latest
  pullPolicy: IfNotPresent

vault:
  # Vault Server address with scheme e.g. https://vault.server.example.com
  address: ""
  # Vault Server Unseal keys, suggested to enter at least 3
  shards: []
  customHeaders: {}
  extraArgs: []

envFrom: []
#  - configMapRef:
#     name: config-map-name
#  - secretRef:
#     name: secret-name

volumeMounts: []
#  - name: config-volume
#    readOnly: true
#    mountPath: "/etc/config-volume"

volumes: []
#  - name: config-volume
#    secret:
#      secretName: vault-unseal-config
