apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "vault-unseal-cronjob.fullname" . }}
  labels:
    {{- include "vault-unseal-cronjob.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "vault-unseal-cronjob.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: {{ .Values.restartPolicy }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - unseal
                - --address={{ required "A address is required for Vault Server" .Values.vault.address }}
                {{- range .Values.vault.shards }}
                - --shard={{ required "A Shard (unseal key) is required" . }}
                {{- end }}
                {{- range $k, $v := .Values.vault.customHeaders }}
                - --custom-header={{ $k }}={{ $v }}
                {{- end }}
                {{- with .Values.vault.extraArgs }}
                  {{- toYaml . | nindent 16 }}
                {{- end }}
              {{- with .Values.envFrom }}
              envFrom:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.volumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          {{- with .Values.volumes }}
          volumes:
            {{- toYaml . | nindent 12}}
          {{- end }}
