name: Release Charts

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: fregante/setup-git-user@v1

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@master
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Helm Chart Docs Github Pages
        uses: omegion/helm-charts-docs@v0.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}